### ISSUE TITLE
Self-signed SSL support

### ISSUE THREAD

**Issue by wico** [tananaev/traccar-manager-android#20]
Hi,

Question: It looks like traccar-manager-android (its okhttp) does not support/implement https with self-signed certificates. Is that correct? Would it be possible to add that as an feature?

**Comment by tananaev** [comment]
Can you explain the reason for not using a valid trusted certificate?

**Comment by wico** [comment]
There are reasons doing that. However, do you have any plans to add support for that?

**Comment by tananaev** [comment]
I don't have any plans at the moment, but I can consider it if you tell me the use case.

**Comment by Beast141** [comment]
Actually - now you can use Lets Encrypt, perfect to create certificates for your server.

**Comment by wico** [comment]
Its on my todo-list, but not done yet. Thus I patched traccar by myself to support self-signed certs. So we can close that thread.
