### ISSUE TITLE
Traccar Manager for android

### ISSUE THREAD

**Issue by sms1515** [tananaev/traccar-manager-android#22]
server 3.7
I can not log my server traccar. I tested my server through the browser on android and all right.

no found many just url configuration options.

**Comment by tananaev** [comment]
English please.

**Comment by sms1515** [comment]
server 3.7
I can not log my server traccar. I tested my server through the browser on android and all right.

no found many just url configuration options.

**Comment by tananaev** [comment]
Can I see a screenshot of your URL in the Traccar Manager app?

**Comment by sms1515** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/22509046/18936581/ec9175bc-85be-11e6-8fb5-3657a0ae7dc7.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/22509046/18936584/f2fad33a-85be-11e6-993e-8594e8c8bf67.jpg)

**Comment by tananaev** [comment]
I get an error:
```
This site can’t be reached

http://pc1.serveftp.com/ is unreachable.
```

**Comment by sms1515** [comment]
try again

**Comment by tananaev** [comment]
Now, I can see server on `http://pc1.serveftp.com:8082/`, but not on `http://pc1.serveftp.com/`.

**Comment by sms1515** [comment]
then already I tried both ways, with and without 8082

**Comment by tananaev** [comment]
You should use with 8082 if that's you server address. You should use same URL as you use to access web interface.

**Comment by sms1515** [comment]
I managed to connect. thank you
