### ISSUE TITLE
How to change traccar  Google Api to OpenStreetMap?

### ISSUE THREAD

**Issue by trinhcanhphuc** [tananaev/traccar-manager-android#29]
I build traccar manager android with traccar server.
I want to Open Street Map from Traccar server show Traccar Manager Android.
Help me!
Thanks.

**Comment by tananaev** [comment]
I'm sure there are existing libraries for that.

You can also take a look at "webview" branch. It's an app based on the web app.

**Comment by trinhcanhphuc** [comment]
Thanks
Thanks

I have found
