### ISSUE TITLE
[Android Web app] device with current position is not reflected on map

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar-manager-android#31]
Once the device is on move with GPS enabled, it is shown on map with movement on web browser. But  in Android Web app, I need to close and reopen the app.

**Comment by tananaev** [comment]
It works for me. What version of Android do you have? Are you sure nothing blocks WebSocket connection from your phone?

**Comment by kirantpatil** [comment]
Now it is working. I don't know what was the issue. I was accessing demo server from both Android and browser from desktop. For now close the issue. If I see any issues then will reopen.
