### ISSUE TITLE
feedback Traccar-Manager-Webview

### ISSUE THREAD

**Issue by Turbovix** [tananaev/traccar-manager-android#32]
@tananaev 
I'm testing Tracca-Manager-Webview and it works fine, while I want to tell you a detail that happens in REPORTS + CONFIGURE, the window needs to be moved sideways to select what you need. It looks like the SETTINGS window is not responsive like the rest of the app that has sliders.

It seems to be more promising than the native Android version, congratulations!

**Comment by tananaev** [comment]
Can I see a screenshot of the issue?

**Comment by Turbovix** [comment]
![screenshot_20161209-184452](https://cloud.githubusercontent.com/assets/3914126/21064109/46c346d2-be40-11e6-8a39-629c731d49a2.png)

**Comment by tananaev** [comment]
Do other dialog boxes look fine?

**Comment by Turbovix** [comment]
Yes, all others are correct!

**Comment by Turbovix** [comment]
Oops, I forgot, the export function does not work! It does not respond to the click!

**Comment by tananaev** [comment]
OK, we'll investigate those issues. Thanks for the information.

**Comment by tananaev** [comment]
Fixed in https://github.com/tananaev/traccar-web/commit/fc74937a487be1f7049cbab79216834f044b6a99.
