### ISSUE TITLE
webview: When zooming, the marker changes the position (center = position, not the "nose")

### ISSUE THREAD

**Issue by amenk** [tananaev/traccar-manager-android#34]
When I pinch-zoom in on the mobile, the marker changes the position. When zoomed out it is south of a main street, when zooming in, north of it (whichout the device moving or position updated)

**Comment by amenk** [comment]
Happens also on the web app. The problem is that the marker has a tiny "nose" - which looks like that is the right position - but the position seems to be the center of the marker instead.

**Comment by tananaev** [comment]
Position is in the center of the marker. "Nose" just shows the direction.

**Comment by amenk** [comment]
Ah okay thanks
