### ISSUE TITLE
webview: Use a different classname / app name

### ISSUE THREAD

**Issue by amenk** [tananaev/traccar-manager-android#35]
What do you think about using a different classname for the webview branch to be able to have both versions of the app installed parallel?

**Comment by tananaev** [comment]
We don't have resources to support two sets of apps.

**Comment by amenk** [comment]
So the webview will replace the standard app?

**Comment by tananaev** [comment]
Yes, it will.

**Comment by tananaev** [comment]
Just want to note one thing here. I will leave a separate branch for original native apps, so anybody would be able to take it and build their own version or extend and modify it.
