### ISSUE TITLE
Change server

### ISSUE THREAD

**Issue by HJvD123** [tananaev/traccar-manager-android#36]
Hi,

after setting the server for the first time there is no way of changing this server settings. Tried removing and reinstalling the manager but no luck. Think the settings are stored somewhere in Android. Could you add a menu for changing the server?

**Comment by tananaev** [comment]
Re-installing the app should definitely bring it back. Alternatively you can also clear the storage from the app manager. It's all mentioned on the first screen.

**Comment by HJvD123** [comment]
Clearing the app storage did the trick for me! Thanks.
