### ISSUE TITLE
Reports tab

### ISSUE THREAD

**Issue by ValeraVi** [tananaev/traccar-manager-android#37]
It is not possible to change the width of columns in Reports tab. So for time stamp is only date is visible; time is not visible.
Other tabs like Devices, State works ok, width of columns can be changed.

**Comment by tananaev** [comment]
It works for me.

**Comment by ValeraVi** [comment]
It seems like all columns of report table has a "style=width: 100px;..." or something else, which prevent them to have the width less that some minimal value (100 px?).
So on big screen, if there are enough space for columns to be wider that that minimal value, it is possible to make column wider, then rest of columns will be smaller, but they can't be smaller than minimal value anyway.
On small screen, all columns already using minimum allowed width, scroll bar already visible. So it is not possible to increase the width of one column, because size of other columns can't be decreased below minimum value.

Is it possible to increase the virtual screen size for table? Because currently, tables, seems like, are trying to fit to real screen size (very small on phone) and calculating all width of all columns, based on real screen size, always hitting the minimal allowed values. If for example real screen size 1000px, then 15 columns with minimum width 100 px will got virtual screen size just to fit those 15 columns with minimum width, i.e. 1500 px; and scroll bar will be available. So it will be not possible to resize the columns. But i think it will be better to give the virtual screen size much bigger: for example 4 times bigger than minimum width, or, may be some fixed, but big value, like 10000 px (for my example above). Scroll bars will be visible in both cases, but at least it will be possible to resize needed column.

Thanks!

**Comment by tananaev** [comment]
Sorry for delay. I have fixed the problem in https://github.com/tananaev/traccar-web/commit/1db0f3fce321a6f22da47998a53f6a5bf7bc7b36.
