### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by GOchispaGO** [tananaev/traccar-manager-android#39]
I'm using TraccarServerDemo4 & TraccarManager2.0

Thanks, it's very good job!!! 

I'm looking for CustonMapLayer/Google Satellite:

https://mt0.google.com/vt/lyrs=s&hl=en&x={x}&y={y}&z={z}&s=Ga

...but we are users, we aren't Admin ;-CC

Will this be updated?

**Comment by tananaev** [comment]
Only admin of the server can configure custom map URL. The main reason is that to use Google Maps, you have to have proper license.

**Comment by GOchispaGO** [comment]
Does it intend that Traccar will have such a license in the future?

...anyway, thanks again for your work Anton!!!

**Comment by tananaev** [comment]
If you want to sponsor it, I'm happy to add the license. It used to cost $10k per year. They don't publish the price publicly anymore, but I would imagine it's the same or even more now.

**Comment by GOchispaGO** [comment]
No thanks, at the moment it is displayed very well with OpenStreetMap   ;-))

... but I wish that one day you receive a call from Google   ;-DD

**Comment by tananaev** [comment]
I wish, but it's unlikely to happen. Closing the issue.
