### ISSUE TITLE
Add Calendar

### ISSUE THREAD

**Issue by GOchispaGO** [tananaev/traccar-manager-android#42]
Testing new feature "TimedGeofences" with Traccar V.10 vía web (server Demo4) is OK.

But using AppTraccarManager V2.0, I can't activate the botton "FileUpload":

https://fotos.subefotos.com/171ba960f543cc23941916b9c57e2450o.jpg

**Comment by tananaev** [comment]
What version of Android are you using?

**Comment by GOchispaGO** [comment]
Android 5.1

**Comment by tananaev** [comment]
@GOchispaGO, I am working on this issue.

**Comment by tananaev** [comment]
I have fixed the problem, but there seems to be another issue in the web interface itself. We'll investigate it further.
