### ISSUE TITLE
Connection error when using domain in the server field

### ISSUE THREAD

**Issue by jalvaradejo** [tananaev/traccar-manager-android#43]
When is use an IP address in the server field it connects OK (example http://127.0.0.1) but if use a domain name (example http://traccar.server.com) or (http://www.traccar.server.com) in the server field is says connection. I check the domains in a browser they work but not in the traccar manager app is that normal ??

**Comment by tananaev** [comment]
Have you checked in the browser on the same mobile device?

**Comment by jalvaradejo** [comment]
Yeah, in the browser it works fine but not in the manager app, not sure why it gives the connection error.

**Comment by tananaev** [comment]
Can you please provide an IP address, so I can check it myself.

**Comment by jalvaradejo** [comment]
this works in app manager http://200.12.65.43:8001 but when I put http://demo.hdmtec.com I dosen´t work in the app manager but if i open it in the phones browser it works.

**Comment by tananaev** [comment]
The second one (http://demo.hdmtec.com/) is not Traccar. It just a web page with Traccar in an iframe. Obviously it won't work like that.

**Comment by jalvaradejo** [comment]
the url (http://demo.hdmtec.com/) is a sub domain pointing to (http://200.12.65.43:8001) its not a webpage with an iframe, I dont know where you got that idea.

**Comment by tananaev** [comment]
Well, that's a lie:
```html
<html><HEAD>

</HEAD><FRAMESET border='0' ROWS='*,1'> <FRAME SRC='http://200.12.65.43:8001/'><FRAME SRC='blank.html'> </FRAMESET> </html>
```

**Comment by jalvaradejo** [comment]
Dude, I'm asking for help, i don't have a reason to lie, i don't know how you got that but hears a screen shot of my domain control panel showing the sub domain, 
![pic1](https://cloud.githubusercontent.com/assets/25756066/22916454/4867bb20-f244-11e6-9e79-12091022bdf3.png)

and I right click and put view source and I get the code of the traccar web server I installed
![source](https://cloud.githubusercontent.com/assets/25756066/22916546/c4bada7c-f244-11e6-962b-8b27f8521599.png)

i have delete the sub.domain and added it several times and the same thing happens, i get an error connection

**Comment by tananaev** [comment]
Just open the page and look at the source:

http://demo.hdmtec.com/

What you probably want to do is to set up DNS to point to the IP address.

**Comment by jalvaradejo** [comment]
you were right it was the DNS config. Thank you
