### ISSUE TITLE
Webview vs Native

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar-manager-android#49]
What are the differences between the two branches?  I would like to know the pro/cons for each so that I can choose which one to use.

- jss

**Comment by tananaev** [comment]
### Webview

Light wrapper around web app.

Pros:
- includes support for all features

Cons:
- slower than native app
- does not look native

### Native

Fully native Android or iOS app.

Pros:
- faster and more responsive
- look native to the platform

Cons:
- includes only basic feature
- not maintained anymore

### Summary

I would prefer to have fully native apps, but we just don't have enough resources to support two additional applications and keep them on par with web interface.

**Comment by jon-stumpf** [comment]
Is there an iOS version of traccar-manager?

**Comment by tananaev** [comment]
Have you tried searching?

https://github.com/tananaev/traccar-manager-ios/

**Comment by jon-stumpf** [comment]
That's embarrassing.  I was looking at your top-level page on GitHub which only shows the 6-most popular and not all 24 of your repositories.  My apologies.
