### ISSUE TITLE
JSON File Issue

### ISSUE THREAD

**Issue by vikasdubeyyy** [tananaev/traccar-manager-android#58]
Where, I will get traccar-manager-android.json ?
OR
I need to create my own .json file from firebase console ?

**Comment by tananaev** [comment]
You should use "regular" build flavor.

**Comment by tananaev** [comment]
Yes.

**Comment by vikasdubeyyy** [comment]
Hi,

How to add google folder in src folder ? (Any specific procedure ?)
I just copied that folder & renamed the packages.

It's showing red. (class & package not found)

<application
    android:name="in.tracker.client.GoogleMainApplication"
    tools:replace="android:name">

</application>

Thanks & Regards





-- 
Thanks & Regards,
Vikas Dubey
Software Developer

*Email:*
*vikasdubeyyy@gmail.com <vikasdubeyyy@gmail.com>*

*Web:*     Facebook <https://www.facebook.com/vikasdubeyyy> / Twitter
<https://twitter.com/vikasdubeyyy> / LinkedIn
<https://www.linkedin.com/in/vikasdubeyyy> / *GooglePlus
<https://plus.google.com/+vikasdubeyyyy/>*
<https://www.linkedin.com/in/vikasdubeyyy>

**Comment by tananaev** [comment]
I'm closing this issue because your question has nothing to do with Traccar project. There are plenty of resources online where you can get help with Android development questions.
