### ISSUE TITLE
When selecting device, it should zoom in the location automatically

### ISSUE THREAD

**Issue by 2SI3NX** [tananaev/traccar-manager-android#62]
Till now, its been very tiresome to view a single device.
When opening the app, it shows map in a zoomed out default position. When clicking on one of the device names - it should by default zoom in automatically to the exact location of the device.

Has this feature not been asked before?
Is this supposed to be requested on https://github.com/tananaev/traccar ?

**Comment by tananaev** [comment]
It should be here:

https://github.com/tananaev/traccar-web
